apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    reloader.stakater.com/auto: "true"
  name: wlm-workloads
spec:
  selector:
    matchLabels:
      app: wlm-workloads
  replicas: 1 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: wlm-workloads
    spec:
      containers:
      - name: wlm-workloads
        image:  trilio/tvr-workloadmgr-api:4.0.1
        command: [ "/bin/sh","-c" ]
        args: [ "/home/rhv/myansible/bin/python3 /home/rhv/myansible/lib64/python3.7/site-packages/workloadmgr/mount_backup_target.py; su vdsm bash -c '/home/rhv/myansible/bin/workloadmgr-workloads --config-file=/etc/workloadmgr/conf/workloadmgr.conf'" ]
        securityContext:
          privileged: true
        volumeMounts:
        - name: tvault-config
          mountPath: /etc/tvault-config/conf
          readOnly: false
        - name: workloadmgr-config
          mountPath: /etc/workloadmgr/conf
        - name: vault-config
          mountPath: /etc/workloadmgr/vault.conf
          subPath: vault.conf
      volumes:
        - name: tvault-config
          configMap:
            name: tvault-config-file
        - name: workloadmgr-config
          configMap:
            name: workloadmgr-config-file
        - name: vault-config
          configMap:
            name: vault-config-file
      imagePullSecrets:
        - name: regcred-trilio
---
apiVersion: v1
kind: Service
metadata:
  name: wlm-workloads
spec:
  ports:
  - name: http
    port: 8785
  - name: websocket
    port: 8888
  selector:
    app: wlm-workloads
  type: ClusterIP
