{{- if .Values.configmap_enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: tvr-secret
  namespace: {{ .Values.namespace }}
  annotations:
    "helm.sh/resource-policy": keep
type: Opaque
data:
  admin: JDJiJDE0JGF1QW04WXR1VTRnN04wRW1wZHFQZ2VWeXg0RXQzbjM5ZDVqL3dhTlh3OGdqWEIybmhXakR1
{{- end -}}
