apiVersion: batch/v1 
kind: Job 
metadata:   
  name: rabbitmq-ha-policy  
  namespace: {{ .Values.namespace }}
  labels:     
    jobgroup: rabbitmq
spec:   
  template:     
    metadata:       
      name: kubejob       
      labels:         
        jobgroup: rabbitmq     
    spec:  
      serviceAccountName: internal-kubectl     
      containers:       
      - name: c         
        image: trstringer/internal-kubectl:latest     
        command:
        - /bin/bash
        - -c
        - |
          sleep 20
          kubectl exec rabbitmq-0 -n trilio -- rabbitmqctl set_policy ha-all "." '{"ha-mode":"all", "ha-sync-mode":"automatic"}' --apply-to all --priority 0
      restartPolicy: OnFailure