apiVersion: v1
kind: ServiceAccount
metadata:
  name: internal-kubectl
  namespace: {{ .Values.namespace }}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: kubectl-internal-role
  namespace: {{ .Values.namespace }}
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: modify-to-sa
  namespace: {{ .Values.namespace }}
subjects:
  - kind: ServiceAccount
    name: internal-kubectl
roleRef:
  kind: Role
  name: kubectl-internal-role
  apiGroup: rbac.authorization.k8s.io
