---
- name: TVM Deployment
  hosts: localhost
  tasks:

  - name: add trilio helm repo
    command: helm repo add trilio https://triliodata.github.io/rhv-ops-script/charts/

  - name: repo update
    shell: helm repo update

  - name: Install Ingress RHV
    command: helm install ingress trilio/ingress --create-namespace  --dependency-update   -f /opt/ansible/values.yaml  --timeout 10m

  - name: Install RabbitMQ    
    command: helm install rabbitmq trilio/rabbitmq  -f /opt/ansible/values.yaml --set namespace=trilio --timeout 10m 

  - name: Install tvault_wlm
    command: helm install tvr trilio/tvault   -f /opt/ansible/values.yaml --set namespace=trilio --timeout 10m 

  - name: Install mariadb
    command: helm install mariadb trilio/mariadb -n trilio

  - name: Install dashboard
    command: helm install dashboard trilio/dashboard 

  - name: Create a directory /opt/manifest/ca if it does not exist
    ansible.builtin.file:
      path: /opt/manifest/ca
      state: directory
      mode: '0775'

  - name: check if CA  exists
    stat: 
      path: /opt/manifest/ca/CA.pem
    register: ca_pem

  - name: Create CA and Certs
    shell: |
      openssl genrsa -des3 -out /opt/manifest/ca/CA.key -passout pass:52T8FVYZJse  2048 
      openssl req -x509 -new -nodes -key /opt/manifest/ca/CA.key -passin pass:52T8FVYZJse  -sha256 -days 1825 -out /opt/manifest/ca/CA.pem -batch
      openssl genrsa -out /opt/manifest/ca/workloadmgr.key 2048
      openssl req -new -key /opt/manifest/ca/workloadmgr.key -out /opt/manifest/ca/workloadmgr.csr -batch
    when: ca_pem.stat.exists == False
    

  - name: signed the certificate for tvault
    shell: |
      echo " 
          authorityKeyIdentifier=keyid,issuer
          basicConstraints=CA:FALSE
          keyUsage = digitalSignature, nonRepudiation, keyEncipherment, dataEncipherment
          subjectAltName = @alt_names
          [alt_names]
          DNS.1 = tvault.com " > /opt/manifest/ca/workloadmgr.ext 
          
      openssl x509 -req -in /opt/manifest/ca/workloadmgr.csr -CA /opt/manifest/ca/CA.pem -CAkey /opt/manifest/ca/CA.key -CAcreateserial -out /opt/manifest/ca/workloadmgr.cert -days 1825 -sha256 -extfile /opt/manifest/ca/workloadmgr.ext  -passin pass:52T8FVYZJse


  - name: signed the certificate for rabbitmq
    shell: |
      echo " 
          authorityKeyIdentifier=keyid,issuer
          basicConstraints=CA:FALSE
          keyUsage = digitalSignature, nonRepudiation, keyEncipherment, dataEncipherment
          subjectAltName = @alt_names
          [alt_names]
          DNS.1 = rabbitmq.tvault.com " > /opt/manifest/ca/rabbitmq.ext 
          
      openssl x509 -req -in /opt/manifest/ca/workloadmgr.csr -CA /opt/manifest/ca/CA.pem -CAkey /opt/manifest/ca/CA.key -CAcreateserial -out /opt/manifest/ca/rabbitmq.cert -days 1825 -sha256 -extfile /opt/manifest/ca/rabbitmq.ext  -passin pass:52T8FVYZJse

  - name: signed the certificate for dashboard
    shell: |
      echo " 
          authorityKeyIdentifier=keyid,issuer
          basicConstraints=CA:FALSE
          keyUsage = digitalSignature, nonRepudiation, keyEncipherment, dataEncipherment
          subjectAltName = @alt_names
          [alt_names]
          DNS.1 = dashboard.tvault.com " > /opt/manifest/ca/dashboard.ext 
          
      openssl x509 -req -in /opt/manifest/ca/workloadmgr.csr -CA /opt/manifest/ca/CA.pem -CAkey /opt/manifest/ca/CA.key -CAcreateserial -out /opt/manifest/ca/dashboard.cert -days 1825 -sha256 -extfile /opt/manifest/ca/dashboard.ext  -passin pass:52T8FVYZJse


  - name: create secrets for CA
    shell: kubectl create secret generic ca-certs --from-file=pem_content=/opt/manifest/ca/CA.pem  --from-file=key_content=/opt/manifest/ca/CA.key -n trilio
    ignore_errors: True

  - name: create secrets for Ingress
    shell: kubectl create secret tls tvault-ingress-tls --namespace trilio --key /opt/manifest/ca/workloadmgr.key --cert /opt/manifest/ca/workloadmgr.cert
    ignore_errors: True

  - name: create secrets for rabbitmq
    shell: kubectl create secret tls rabbit-tls-secret --namespace trilio --key /opt/manifest/ca/workloadmgr.key --cert /opt/manifest/ca/rabbitmq.cert
    ignore_errors: True

  - name: create secrets for dashboard
    shell: kubectl create secret tls tls-secret --namespace kubernetes-dashboard --key /opt/manifest/ca/workloadmgr.key --cert /opt/manifest/ca/dashboard.cert
    ignore_errors: True 


 
